// Generated by Wrangler on Sun Sep 29 2024 22:26:44 GMT+0900 (GMT+09:00)
// by running `wrangler types`

// biome-ignore lint/correctness/noUnusedVariables: <explanation>
interface Env {
	GOOGLE_AUTH_CALLBACK_URL: string;
	GOOGLE_AUTH_CLIENT_ID: string;
	GOOGLE_AUTH_CLIENT_SECRET: string;
	SESSION_SECRET: string;
	// biome-ignore lint/correctness/noUndeclaredVariables: <explanation>
	DB: D1Database;
}
